#
# CREATION KIT PLATFORM EXTENDED CUSTOM THEME SETTINGS
#
# NOTICE: This file should be in the root folder of the game. The missing ones will be equal black color (0,0,0). 
# This theme will only be included if the dark theme and the special index of this theme are included.
# bUIDarkTheme=true
# uUIDarkThemeId=3
#
[Colors]
rDefault=[184,184,184]											# The main color of the windows
rListView_BkColor=[238,238,238]									# The color of the workspace ListView
rTreeView_BkColor=[238,238,238]									# The color of the workspace TreeView
rEdit_BkColor=[238,238,238]										# The color of the workspace Edit, (also progressbar)
rEdit_BkColor_Disabled=[238,238,238]							# The color of the workspace Edit if it is disabled
rText_1=[141,141,141]											# The color of the text, which is mostly intended for disabled controls
rText_2=[96,96,96]												# It is used only in the conditions field
rText_3=[32,32,32]												# The main color of the text
rText_4=[16,16,16]												# The main color of the input text or focused, hot text
rMDIWindow=[123,123,123]										# A useless part of the main window
rDefault_Gradient_Start=[229,229,229]							# Body for buttons, combobox and etc
rDefault_Gradient_End=[190,190,190]								# Body for buttons, combobox and etc
rDivider_Highlighter_Disabled_Gradient_Start=[184,184,184]		# Highlighter if the control (buttons, combobox and etc) is disabled (1px)
rDivider_Highlighter_Disabled_Gradient_End=[192,192,192]		# Highlighter if the control (buttons, combobox and etc) is disabled (1px)
rDivider_Color=[81,81,81]										# The frame for the control (1px)
rDivider_Color_Disabled=[140,140,140]							# The frame for the control if is disabled (1px)
rDivider_Highlighter=[246,246,246]								# -- Outdated
rDivider_Highlighter_Hot=[246,246,246]							# -- Outdated
rDivider_Color_Ver2=[153,153,153]								# It is used in groupbox, box, progressbar frame or a separator in the menu (1px)
rDivider_Color_Disabled_Ver2=[196,196,196]						# It is used in groupbox frame if is disabled (1px)
rDivider_Highlighter_Ver2=[212,212,212]							# It is used in groupbox frame or a separator in the menu (Highlighter) (1px)
rDivider_Highlighter_Disabled_Ver2=[164,164,164]				# It is used in groupbox frame if is disabled (Highlighter) (1px)
rDivider_Highlighter_Gradient_Start=[184,184,184]				# The main highlighter before the frame of any control
rDivider_Highlighter_Gradient_End=[199,199,199]					# The main highlighter before the frame of any control
rDivider_Highlighter_Hot_Gradient_Start=[184,184,184]			# The main highlighter before the frame of any control if the mouse is pointed
rDivider_Highlighter_Hot_Gradient_End=[100,125,154]				# The main highlighter before the frame of any control if the mouse is pointed
rDivider_Highlighter_Pressed=[83,147,190]						# The main highlighter before the frame of any control when clicked
rButton_Pressed_Gradient_Start=[139,139,139]					# The color of the button when it is pressed
rButton_Pressed_Gradient_End=[130,130,130]						# The color of the button when it is pressed
rButton_Hot_Gradient_Start=[239,239,239]						# The color of the button if the mouse is pointed
rButton_Hot_Gradient_End=[200,200,200]							# The color of the button if the mouse is pointed
rButton_Pressed_Divider=[121,121,121]							# The color of the button frame when it is pressed
rButton_Light_Disabled_Divider=[223,223,223]					# The strip on top that creates the effect of light falling from above when the button is disabled
rButton_Disabled_Gradient_Start=[207,207,207]					# The color of the button if is disabled
rButton_Disabled_Gradient_End=[187,187,187]						# The color of the button if is disabled
rCheckBox_Gradient_Start=[111,111,111]							# The color of the square
rCheckBox_Gradient_End=[81,81,81]								# The color of the square
rScrollBar_Gradient_Start=[221,221,221]							# Scrollbar color (back)
rScrollBar_Gradient_End=[189,189,189]							# Scrollbar color (back)
rScrollBar_Thumb_Gradient_Start=[161,161,161]					# Scrollbar color (Thumb)
rScrollBar_Thumb_Gradient_End=[129,129,129]						# Scrollbar color (Thumb)
rScrollBar_Thumb_Gradient_Hot_Start=[171,171,171]				# Scrollbar color (Thumb) if the mouse is pointed or retention
rScrollBar_Thumb_Gradient_Hot_End=[139,139,139]					# Scrollbar color (Thumb) if the mouse is pointed or retention
rScrollBar_Thumb_Highlighter=[174,174,174]						# The strip on top that creates the effect of light falling from above
rScrollBar_Thumb_Highlighter_Hot=[184,184,184]					# The strip on top that creates the effect of light falling from above when the mouse is pointed or retention
rShape=[76,76,76]												# The main color of any shape: arrows for the most part
rShape_Hot=[123,198,225]										# The main color of any shape: arrows for the most part if the mouse is pointed
rShape_Pressed=[55,55,55]										# The main color of any shape: arrows for the most part when is clicked
rShape_Disabled=[129,129,129]									# The main color of any shape: arrows for the most part if is disabled
rShape_Shadow=[220,220,220]										# The color of the shadow that the figure casts
rShape_Shadow_Disabled=[190,190,190]							# The color of the shadow that the figure casts if is disabled
rProgress_Fill_Gradient_Start=[163,57,168]						# The main color of the progress bar
rProgress_Fill_Gradient_End=[133,48,137]						# The main color of the progress bar
rProgress_Fill_Highlighter=[186,71,192]							# The outline inside of the progress bar
rProgress_Fill_Highlighter_Up=[173,62,179]						# The strip on top that creates the effect of light falling from above inside of the progress bar
rBorder_Window=[0,144,255]										# It is only used pagecontrol
rStatusBar_Back=[128,128,128]									# Background statusbar
rStatusBar_Text=[24,24,24]										# Text color statusbar
rCaption_Text=[20,20,20]										# It is only used pagecontrol
rHeader_Normal_Gradient_Start=[166,166,166]						# The color of the column name in listview
rHeader_Normal_Gradient_End=[147,147,147]						# The color of the column name in listview
rHeader_Hot_Gradient_Start=[176,176,176]						# The color of the column name in listview if the mouse is pointed
rHeader_Hot_Gradient_End=[157,157,157]							# The color of the column name in listview if the mouse is pointed
rListView_Owner_Selected=[242,176,173]							# Background color when selecting a field, the color itself is mixed with the back by 40% (only for ownerdraw)
rSelectedItem_Back=[117,197,255]								# -- Outdated
rSelectedItem_Text=[32,32,32]									# -- Outdated

[Assets]
# The color that will become transparent. I agree it's all outdated, hello Windows 95. 
# But this approach is used. In this regard, you need to make a picture on the background of this color.
# This will allow for smooth transitions.
rMaskToolbar=[192,192,192]
# The path to your picture for toolbar (only 24bits and .bmp)
sImageForToolbar='toolbar.bmp'
# The color that will become transparent. I agree it's all outdated, hello Windows 95. 
# But this approach is used. In this regard, you need to make a picture on the background of this color.
# This will allow for smooth transitions.
rMaskToolbarNavMesh=[192,192,192]
# The path to your picture for toolbar (only 24bits and .bmp)
sImageForToolbarNavMesh='navmesh.bmp'
# The color that will become transparent. I agree it's all outdated, hello Windows 95. 
# But this approach is used. In this regard, you need to make a picture on the background of this color.
# This will allow for smooth transitions.
rMaskIcons=[0,128,128]
# The path to your picture for icon forms (only 24bits and .bmp)
sImageForIcons='icons.bmp'
# The Data Window uses its own checkbox icons, if you need black ones, set true
bNeedDarkCheckboxInData=true